<?php

/**
 * Implements hook_theme().
 */
function user_list_theme($existing, $type, $theme, $path) {
  return [
    'user_list' => [
      'variables' => ['users' => [], 'ajax_form' => NULL],
      'template' => 'user-list',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for user_list.html.twig.
 */
function user_list_preprocess_user_list(&$variables) {
  // Load the form for AJAX interaction.
  $variables['ajax_form'] = \Drupal::formBuilder()->getForm('Drupal\user_list\Form\UserListAjaxForm');
}
